function [ ] = problem2( )
% Each new term in the Fibonacci sequence is generated by adding the
% previous two terms. By starting with 1 and 2, the first 10 terms will be:
%
%       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% By considering the terms in the Fibonacci sequence whose values do not
% exceed four million, find the sum of the even-valued terms.

fprevious=2;
fprevious2=1;
sum=2;

while (true)
    fcurrent = fprevious+fprevious2;
    % fprintf(1, '%d %d %d \n', fcurrent, fprevious, fprevious2);
    if (fcurrent>4000000) break;
    end
    if ((mod(fcurrent,2)==0))
        sum=sum+fcurrent;
    end
    fprevious2=fprevious;
    fprevious=fcurrent;
end
fprintf(1,'the sum of all even fibonacci numbers \n');
fprintf(1,'under 4 million is %d \n',sum );
end

